### ISSUE TITLE
Add custom files to the bundle

### ISSUE THREAD

**Issue by avi12** [NekitCorp/chrome-extension-svelte-typescript-boilerplate#11]
I wish to add some [files](https://github.com/guest271314/persistent-serviceworker/tree/main/chromium_extension_web_accessible_resources_iframe_message_event) that interface directly with `background/index.ts`, however they're not supposed to be imported
Is it possible in this boilerplate?

**Comment by NekitCorp** [comment]
Maybe I didn’t quite understand the problem, but why not put the reusable functions into separate modules and import them in `background/index.ts` and in some files, like `storage.ts` https://github.com/NekitCorp/chrome-extension-svelte-typescript-boilerplate/blob/main/src/background/index.ts?

**Comment by avi12** [comment]
The thing is that [this line](https://github.com/guest271314/persistent-serviceworker/blob/c97f3092b099c33d43a86d1e2add176238e1cc3b/chromium_extension_web_accessible_resources_iframe_message_event/background.js#L51) expects a certain following path
So I was wondering, is there a way that I could have a predetermined path to a file?

**Comment by NekitCorp** [comment]
Yes, you can:

1. `import`

`src/background/index.ts`:
```ts
import data from "../data.json";

chrome.runtime.onInstalled.addListener(() => {
    console.log(data);
});
```

<img width="230" alt="image" src="https://user-images.githubusercontent.com/15874982/208362758-40b19e66-a899-4dc6-a34a-8275be0e1250.png">

2. `public` folder

Create `public` folder in root project directory, and create `data.json` inside `public` folder.

`src/background/index.ts`:
```ts
chrome.runtime.onInstalled.addListener(() => {
    const url = chrome.runtime.getURL("data.json");

    fetch(url)
        .then((res) => res.json())
        .then(console.log);
});
```

the result is the same as in option 1

Output: 
<img width="500" alt="image" src="https://user-images.githubusercontent.com/15874982/208363471-2df03f50-0114-4d01-be0b-d02fc07b6784.png">
