### ISSUE TITLE
HMR for svelte components injected into page through content script is not working

### ISSUE THREAD

**Issue by RafatRifaie** [NekitCorp/chrome-extension-svelte-typescript-boilerplate#17]
So im working on a settings menu that is supposed to be shown to user on a button click.
Im running in dev mode, refresh the page, open the settings menu, and start changing my svelte file, but none of the changes reflect in the dom for the settings menu component. 
Is this normal behavior?

* Note: im not using typescript
package.json
`{
    "name": "lets-kick-it",
    "version": "3.0.0",
    "type": "module",
    "repository": {
        "type": "git",
        "url": "https://github.com/nekitcorp/chrome-extension-svelte-typescript-boilerplate.git"
    },
    "scripts": {
        "dev": "vite",
        "build": "vite build"
    },
    "devDependencies": {
        "@types/chrome": "0.0.200",
        "sass": "^1.62.1",
        "svelte": "3.52.0",
        "svelte-check": "2.9.2",
        "svelte-preprocess": "4.10.7",
        "vite": "^4.3.9",
        "@sveltejs/vite-plugin-svelte": "1.1.0",
        "@crxjs/vite-plugin": "^1.0.14"
    }
}
`

**Comment by NekitCorp** [comment]
Hi, unfortunately it's very hard to say what is the reason without the source code and other possible third party factors. Is it possible for you to make a minimally reproducible example and put it on any online code editor?

https://github.com/NekitCorp/chrome-extension-svelte-typescript-boilerplate/assets/15874982/5484aa08-84f8-442e-9519-c05d9783e4ce
