### ISSUE TITLE
Add Manifest V2 support

### ISSUE THREAD

**Issue by avi12** [NekitCorp/chrome-extension-svelte-typescript-boilerplate#2]
For as long as Firefox still does not support Manifest V3
For now, I'm using the not-so-elegant tool that I developed [build-for-browser](/avi12/build-for-browser), which merely modifies the `manifest.json` of a given ZIP and spits out a new Manifest V2-compatible ZIP

**Comment by NekitCorp** [comment]
Sorry, but I don't want to complicate the project. The project does not take into account a lot of things, but it is a template for starting.
