### ISSUE TITLE
How to add assets images to extension?

### ISSUE THREAD

**Issue by KolyStudio** [NekitCorp/chrome-extension-svelte-typescript-boilerplate#23]
Hi, I'm trying to add images to the extension, but when I put them in the assets folder, nothing happens, they are not exported to the dist folder.

**Comment by NekitCorp** [comment]
Hello, it depends on where you want to use the image.

1. Use in popup/sidepanel/options.

In this case, you can simply put the image next to the component and import it, for example:

```js
import imgUrl from "./svelte.png";

...

<img src={imgUrl} width="300" height="100" alt="Svelte logo" />
```

2. Use in content script

In this case, you need to familiarize yourself with [Manifest - Web Accessible Resources](https://developer.chrome.com/docs/extensions/mv3/manifest/web_accessible_resources/), for examaple:

Create `public` folder in root folder and put an image there. After that you can get a link to it using [chrome.runtime.getURL](https://developer.chrome.com/docs/extensions/reference/runtime/#method-getURL):

```js
const imgUrl = chrome.runtime.getURL("/svelte.png");

...

<img src={imgUrl} width="300" height="100" alt="Svelte logo" />
```

**Comment by KolyStudio** [comment]
When i do npm run build, images are not added to release folder
