### ISSUE TITLE
"Waiting for service worker" popup with npm run dev on fresh install

### ISSUE THREAD

**Issue by Glench** [NekitCorp/chrome-extension-svelte-typescript-boilerplate#29]
<img width="109" alt="Screenshot 2024-10-23 at 9 18 26 AM" src="https://github.com/user-attachments/assets/73f2ca44-8369-4c27-9ca4-040ac5c81c3f">

When I clone the repo from source, run `npm install`, then `npm run dev` and load the extension unpacked from the `dist/` folder, I see an endless reloading "Waiting for service worker" when I click the extension's icon to open the popup/options page. I'd expect instead to see the correct popup/options page. If I run `npm run build` the popup works fine and I see the +/- count demo.

I'm on Chrome for Mac 130.0.6723.59.

**Comment by NekitCorp** [comment]
Hello! Yes, this is a known issue in the new version 130 of Chrome. I have updated the package, please try again in the new version.

You can read more about the issue here – https://github.com/crxjs/chrome-extension-tools/issues/918

**Comment by Glench** [comment]
Marvelous, thank you so much! Changing the dependencies of my project to the ones listed in this package fixed it!
