### ISSUE TITLE
Question about different builds

### ISSUE THREAD

**Issue by avi12** [NekitCorp/chrome-extension-svelte-typescript-boilerplate#3]
What's the difference between `vite build` and [web-ext build](https://extensionworkshop.com/documentation/develop/web-ext-command-reference/#web-ext-build)?

**Comment by NekitCorp** [comment]
I'm not very familiar with `web-ext`, this boilerplate uses `Svelte` for which [Vite](https://svelte.dev/docs#compile-time) is convenient as a build system.
