### ISSUE TITLE
Refused to load script error

### ISSUE THREAD

**Issue by Glench** [NekitCorp/chrome-extension-svelte-typescript-boilerplate#30]
I've been using this repo for a while now for my extensions and they've been working fine for years but suddenly they're all getting "Refused to load the script" errors in the content scripts like the following:

```"Refused to load the script 'chrome-extension://a30799cf-d346-49a0-b39a-45e132f42309/vendor/vite-client.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback."``` This error is generated from `content/index.ts-loader.js`. I don't have a CSP in my extension anywhere and the site the content script is loaded on doesn't either.

I didn't change my code at all so I'm wondering if chrome recently changed something that would break this? Does anyone know why this is happening or how to fix it? I've thought about upgrading to the latest version of this repo but there was a breaking error in #29 it seems.

I do notice that when I click on the URL in the error (`chrome-extension://a30799cf...`) it takes me to a slightly different URL: `chrome-extension://kbiikhokgdijnepdkahandpoaaepochg/vendor/vite-client.js`. I'm wondering if the content security policy error is happening because chrome.runtime.getURL is returning a different URL than the actual extension ID.

**Comment by NekitCorp** [comment]
https://github.com/NekitCorp/chrome-extension-svelte-typescript-boilerplate/issues/29#issuecomment-2432210097

**Comment by Glench** [comment]
Yes! Closing with the fix of #29
