### ISSUE TITLE
Excluding certain files

### ISSUE THREAD

**Issue by avi12** [NekitCorp/chrome-extension-svelte-typescript-boilerplate#4]
I ran into a situation where I need to customize the build script so only the Chrome version will have certain files, as well as only the Chrome's Manifest will list those files

E.g.
```
src
  chrome-specific
    a.js
    b.js
```
```json
{
  "content_scripts": [
    {
      "matches": ["https://domain.com/*"],
      "js": ["chrome-specific/a.js", "chrome-specific/b.js"]
    }
  ]
}
```

**Comment by NekitCorp** [comment]
I'm sorry, but I think this is out of the scope of this boilerplate project.
