### ISSUE TITLE
Disabling module for content script

### ISSUE THREAD

**Issue by freb** [NekitCorp/chrome-extension-svelte-typescript-boilerplate#7]
When you add additional imports to the [content script](https://github.com/NekitCorp/chrome-extension-svelte-typescript-boilerplate/blob/main/src/pages/content/index.ts) for things other than types, the output js file is a module that contains import statements. The chrome console complains about these since it doesn't appear that content scripts support modules:

![image](https://user-images.githubusercontent.com/1723508/196809319-a2641e83-56ea-4bf5-91eb-a4ee7f400750.png)

Do you have a solution for using commonjs output for the content script?

A follow-up question. Once the script portion of the content-script is working correctly, do you have any guidance on injecting a svelte component into a page (such as an overlay component)? I'm assuming I will run into that next but am happy to cross that bridge when I come to it.

**Comment by NekitCorp** [comment]
Hi, sorry for the long answer, was looking for a better solution.

As far as I know, `Vite` is not quite suitable for building a single bundle file. I tried to find some workaround for this, you can use dynamic import like in this repository https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/blob/main/src/pages/content/index.ts and add custom vite import plugin https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/blob/main/utils/plugins/custom-dynamic-import.ts and manually add styles to the page. I'm not sure there will be more problems in the future :(

So I think it's better to use another bundler, like `rollup` in a previous version of this project. I created a thread with an example: https://github.com/NekitCorp/chrome-extension-svelte-typescript-boilerplate/tree/issue-7

Output:
<img width="210" alt="image" src="https://user-images.githubusercontent.com/15874982/197126889-f747d846-1aca-48f2-add5-70e0de81a9f5.png">

Some extension page overlay component:
<img width="776" alt="image" src="https://user-images.githubusercontent.com/15874982/197127072-d165fa96-bbe0-4399-87db-159e390fddbb.png">

**Comment by freb** [comment]
Thanks so much for the response. I'll take a look and let you know how it goes. I'll close this issue once I've had a chance to check it out and share any thoughts.

**Comment by freb** [comment]
After taking some time to learn how Vite and Rollup differ, it makes total since to ditch Vite altogether, especially since there is not reloading for extensions (at least that I'm aware of).

Thanks again for your help on this.
